name: Microservices deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  general:
    name: General view
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Checking the place
        run: |
          ls -l
  addAdult:
    name: AddAdult Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ejercicios/video9/AddAdult
    steps:
     - name: Check out the repo
       uses: actions/checkout@v3
 #    - name: Azure Login
 #      uses: Azure/login@v1.4.6
 #      with:
 #        creds: ${{ secrets.AZURE_CREDENTIALS }} 
     - name: Checking the place
       run: |
         ls -l
  addChildren:
    name: AddChildren Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ejercicios/video9/AddChildren
    steps:
 #     - name: Check out the repo
 #       uses: actions/checkout@v3
      - name: Checking the place
        run: |
          ls -l
